#SPDX-License-Identifier: MIT-0
---
# Include vars and define needeed 
- name: Include appropriate vars for OS family
  ansible.builtin.include_vars: "{{ os_specific_vars }}"
  with_first_found:
    - "./vars/{{ ansible_distribution | lower | replace(' ', '_') }}-{{ ansible_distribution_version }}.yml"
    - "./vars/{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "./vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_version }}.yml"
    - "./vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "./vars/{{ ansible_os_family | lower }}.yml"
    - "./defaults/main.yml"
  loop_control:
    loop_var: os_specific_vars

- name: Download cri-o GPG key
  become: true
  ansible.builtin.get_url:
    url: "{{ cri_o_install_gpg_key }}"
    dest: "{{ cri_o_install_tmp_local_path }}"
    owner: root
    group: root
    mode: "0644"

- name: Convert CRI-O GPG key to binary format
  ansible.builtin.shell: "gpg --dearmor -o {{ cri_o_install_gpg_key_local_path }} {{ cri_o_install_tmp_local_path }}"
  args:
    creates: "{{ cri_o_install_gpg_key_local_path }}"

- name: Remove temporary CRI-O GPG key
  become: true
  ansible.builtin.file:
    path: "{{ cri_o_install_tmp_local_path }}"
    state: absent


- name: Add CRI-O repository
  ansible.builtin.copy:
    dest: "{{ cri_o_install_sources }}"
    content: "{{ cri_o_install_apt_repository }}"
    owner: root
    group: root
    mode: "0644"

- name: Install CRI-O
  become: true
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
  loop: "{{ cri_o_install_apt }}"

- name: Check installed runc version
  ansible.builtin.command:
    cmd: runc --version
  register: runc_version
  ignore_errors: true
  changed_when: false

- name: Install runc only if not present
  become: true
  ansible.builtin.apt:
    name: "{{ cri_o_install_runtime }}"
    state: present
  when: runc_version is failed

- name: Ensure /etc/crio/crio.conf.d exists
  ansible.builtin.file:
    path: "{{ cri_o_install_conf_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure CRI-O is started and enabled at boot.
  ansible.builtin.service:
    name: crio
    state: "{{ cri_o_install_service_state }}"
    enabled: "{{ cri_o_install_service_enabled }}"
