#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/master
- name: Check Jenkins server is running
  ansible.builtin.systemd:
    name: jenkins
    enabled: true
    state: started
  register: jenkins_service

- name: Get info from Jenkins master
  ansible.builtin.debug:
    msg: >
      Jenkins service is {{ 'running' if jenkins_service.status.ActiveState == 'active' else 'not running' }}.
