#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/init-cluster
- name: Ensure kubelet is started and enabled at boot.
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true

- name: Check if Kubernetes has already been initialized.
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Configure Calico networking.
  ansible.builtin.command: "kubectl apply -f {{ kubernetes_calico_manifest_file }}"
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  when: kubernetes_pod_network.cni == 'calico'
  until: calico_result is not failed
  retries: 12
  delay: 5

# Set up nodes.
- name: Get the kubeadm join command from the Kubernetes control plane.
  ansible.builtin.command: kubeadm token create --print-join-command
  changed_when: false
  when: kubernetes_role == 'control_plane'
  register: kubernetes_join_command_result

- name: Set the kubeadm join command globally.
  ansible.builtin.set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
      {{ kubernetes_join_command_extra_opts }}
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Add node
  ansible.builtin.include_tasks: add-node.yml
  when: kubernetes_role == 'node'
